sources:
- repo: https://github.com/jacebrowning/gdm-demo
  name: gdm_3
  rev: 75bb55819c6f1017bf9a450c5e58122e73ffc69d
  link: src/gdm_c
- repo: https://github.com/jacebrowning/gdm-demo
  name: gdm_4
  rev: master
