sources:
- repo: https://github.com/jacebrowning/gdm-demo
  name: gdm_3
  rev: b44a5a4a5faa338935e8eccaf288ad86986c553f
  link: src/gdm_c
- repo: https://github.com/jacebrowning/gdm-demo
  name: gdm_4
  rev: master
