sources:
- repo: https://github.com/jacebrowning/gdm-demo
  name: gdm_3
  rev: 050290bca3f14e13fd616604202b579853e7bfb0
  link: src/gdm_c
- repo: https://github.com/jacebrowning/gdm-demo
  name: gdm_4
  rev: master
