language: python
python:
- 3.3
- 3.4
install:
- pip install coveralls scrutinizer-ocular
before_script:
- git fetch origin acca7ecce6cc214a7e68887656e49cfc6c718a51
- make env
- make depends-ci
script:
- make ci
after_success:
- coveralls
- ocular
notifications:
  email:
    on_success: never
    on_failure: change
