language: python
python:
- 3.3
- 3.4
install:
- pip install coveralls scrutinizer-ocular
before_script:
- make env
- make depends-ci
- git fetch origin example-branch
- git fetch origin example-branch-2
script:
- make ci
after_success:
- coveralls
- ocular
notifications:
  email:
    on_success: never
    on_failure: change
